
-- unit
MSG_UNIT_UNSELECTED = "MSG_UNIT_UNSELECTED"

-- map
MSG_MAP_UNSELECTED = "MSG_MAP_UNSELECTED"

-- public
MSG_ADD_TEST_UNIT = "MSG_ADD_TEST_UNIT"

MSG_UNSELECTED = "MSG_UNSELECTED"
MSG_REMOVE_UNIT = "MSG_REMOVE_UNIT"
MSG_ADD_UNIT = "MSG_ADD_UNIT"
MSG_UPDATE_UNIT = "MSG_UPDATE_UNIT"
